# Generated by Django 6.0.6 on 2026-07-22 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figurine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('outil', models.CharField(choices=[('pinceau', 'Pinceau'), ('bombe', 'Bombe'), ('aerographe', 'Aérographe'), ('autre', 'Autre')], max_length=20)),
                ('ordre', models.IntegerField()),
                ('figurine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='figurines.figurine')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
